// This file is part of the ArmoniK project
// 
// Copyright (C) ANEO, 2021-2026. All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq.Expressions;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;

using ArmoniK.Extensions.CSharp.Client.Common.Generic;

namespace ArmoniK.Extensions.CSharp.Client.Queryable;

/// <summary>
///   Class in charge of the execution of a query built with an IQueryable
/// </summary>
/// <typeparam name="TPage">The type of page of elements returned by the query.</typeparam>
/// <typeparam name="TSource">The type of the requested instances.</typeparam>
/// <typeparam name="TField">The type of the paginated instances.</typeparam>
/// <typeparam name="TFilterOr">The type of the protobuf instance that represents a logical OR node.</typeparam>
/// <typeparam name="TFilterAnd">The type of the protobuf instance that represents a logical AND node.</typeparam>
/// <typeparam name="TFilterField">The type of the protobuf instance that describe a filter on a single property.</typeparam>
internal abstract class QueryExecution<TPage, TSource, TField, TFilterOr, TFilterAnd, TFilterField>
  where TField : new()
  where TFilterOr : new()
  where TFilterAnd : new()
{
  private QueryExpressionTreeVisitor<TSource, TField, TFilterOr, TFilterAnd, TFilterField>? visitor_;

  /// <summary>
  ///   Not null when an extension method retuning TSource? has been applied
  ///   on the IQueryable instance.
  /// </summary>
  public Func<IAsyncEnumerable<TSource>, TSource?>? FuncReturnNullableTSource
    => visitor_?.FuncReturnNullableTSource;

  /// <summary>
  ///   Not null when an extension method retuning TSource has been applied
  ///   on the IQueryable instance.
  /// </summary>
  public Func<IAsyncEnumerable<TSource>, TSource>? FuncReturnTSource
    => visitor_?.FuncReturnTSource;

  /// <summary>
  ///   The pagination properties generated by the latest query execution
  /// </summary>
  internal Pagination<TFilterOr, TField> PaginationInstance { get; private set; } = new();

  /// <summary>
  ///   Visit the entire Expression Tree of a query
  /// </summary>
  /// <param name="expression">The Expression Tree</param>
  /// <exception cref="InvalidExpressionException">When the query is invalid.</exception>
  public void VisitExpression(Expression expression)
  {
    try
    {
      visitor_ = CreateQueryExpressionTreeVisitor();
      visitor_.VisitTree(expression);
    }
    catch (Exception ex)
    {
      LogError(ex,
               "Invalid query: " + expression);
      throw new InvalidExpressionException("Invalid query: " + expression,
                                           ex);
    }
  }

  /// <summary>
  ///   Execute the query asynchronously by seamlessly fetching several pages of results.
  /// </summary>
  /// <param name="cancellationToken">The cancellation token</param>
  /// <returns>An asynchronous enumerable of the results.</returns>
  /// <exception cref="InvalidOperationException">When the Expression Tree has not been visited beforehand.</exception>
  public async IAsyncEnumerable<object> ExecuteAsync([EnumeratorCancellation] CancellationToken cancellationToken = default)
  {
    if (visitor_ == null)
    {
      throw new InvalidOperationException("VisitExpression() must be called before ExecuteAsync()");
    }

    if (visitor_.Filters == null)
    {
      yield break;
    }

    PaginationInstance = CreatePaginationInstance(visitor_);

    var   total = 0;
    TPage page;
    do
    {
      page = await RequestInstancesAsync(PaginationInstance,
                                         cancellationToken)
               .ConfigureAwait(false);
      var elements = GetPageElements(PaginationInstance,
                                     page);
      if (elements.Length == 0)
      {
        break;
      }

      total += elements.Length;
      foreach (var element in elements)
      {
        yield return element!;
      }

      if (total >= GetTotalPageElements(page))
      {
        break;
      }

      PaginationInstance.Page++;
    } while (true);
  }

  protected abstract void LogError(Exception ex,
                                   string    message);

  protected abstract Task<TPage> RequestInstancesAsync(Pagination<TFilterOr, TField> pagination,
                                                       CancellationToken             cancellationToken);

  protected abstract QueryExpressionTreeVisitor<TSource, TField, TFilterOr, TFilterAnd, TFilterField> CreateQueryExpressionTreeVisitor();

  protected abstract Pagination<TFilterOr, TField> CreatePaginationInstance(QueryExpressionTreeVisitor<TSource, TField, TFilterOr, TFilterAnd, TFilterField> visitor);

  protected abstract int GetTotalPageElements(TPage page);

  protected abstract object[] GetPageElements(Pagination<TFilterOr, TField> pagination,
                                              TPage                         page);
}
